import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { parseTaskBrief } from "../codex-orchestration/shared/paseo-team-policy/brief.mjs";
import { blockReasonForTool, detectRole, gitAuthorityBlockReason, supervisorCreateAgentBlockReason, ownedScopeBlockReason } from "../codex-orchestration/shared/paseo-team-policy/policy.mjs";
const repo = path.resolve(import.meta.dirname, "..");
const valid = parseTaskBrief(`PASEO_TEAM_TASK_V3_BEGIN\nTASK_ID: T-CODEX\nMODE: write\nOWNED_SCOPE: codex-orchestration, test\nEDIT_AUTHORITY: allowed\nCOMMIT_AUTHORITY: allowed\nPUSH_TASK_BRANCH_AUTHORITY: allowed\nPASEO_TEAM_TASK_V3_END`);
assert.equal(process.env.PASEO_CODEX_ROLE, undefined);
process.env.PASEO_CODEX_ROLE = "worker"; assert.equal(detectRole(), "worker");
assert.match(blockReasonForTool("worker", null, "Bash", { command: "echo x" }, repo), /read-only/);
assert.match(blockReasonForTool("reviewer", valid, "apply_patch", { command: "*** Update File: README.md" }, repo), /read-only/);
assert.match(ownedScopeBlockReason(valid, "README.md", repo), /outside OWNED_SCOPE/);
assert.equal(blockReasonForTool("worker", valid, "apply_patch", { command: "*** Update File: test/new.mjs" }, repo), null);
assert.match(gitAuthorityBlockReason("git push origin main", { pushTaskBranch: true }, "T-CODEX"), /branch-scoped/);
assert.equal(gitAuthorityBlockReason("git push -u origin HEAD:refs/heads/agent/T-CODEX", { pushTaskBranch: true }, "T-CODEX"), null);
assert.match(supervisorCreateAgentBlockReason({ provider: "codex-worker/x", labels: { purpose: "recovery", recovery_for: "p" }, settings: { thinkingOptionId: "high" } }), /codex-lead/);
assert.equal(supervisorCreateAgentBlockReason({ provider: "codex-lead/x/y", labels: { purpose: "recovery", recovery_for: "p" }, settings: { thinkingOptionId: "high" } }), null);
const home = mkdtempSync(path.join(tmpdir(), "paseo-codex-hook-")); mkdirSync(path.join(home, "hooks"));
const run = (name, event) => spawnSync(process.execPath, [path.join(repo, "codex-orchestration/shared/paseo-team-policy", name)], { env: { ...process.env, TMPDIR: home, PASEO_CODEX_ROLE: "worker" }, input: JSON.stringify(event), encoding: "utf8" });
assert.equal(run("user-prompt-submit.mjs", { session_id: "s", prompt: "plain" }).status, 0);
const denied = run("pre-tool-use.mjs", { session_id: "s", cwd: repo, tool_name: "Bash", tool_input: { command: "git push origin main" } });
assert.equal(denied.status, 0); assert.match(denied.stdout, /permissionDecision.*deny/);
console.log("[codex-policy] tests passed");
