import assert from "node:assert/strict";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { parseTaskBrief } from "../codex-orchestration/shared/paseo-team-policy/brief.mjs";
import { blockReasonForTool, detectRole, gitAuthorityBlockReason, ownedScopeBlockReason } from "../codex-orchestration/shared/paseo-team-policy/policy.mjs";
const repo = path.resolve(import.meta.dirname, "..");
const valid = parseTaskBrief(`PASEO_TEAM_TASK_V3_BEGIN\nTASK_ID: T-CODEX\nMODE: write\nOWNED_SCOPE: codex-orchestration, test\nEDIT_AUTHORITY: allowed\nCOMMIT_AUTHORITY: allowed\nPUSH_TASK_BRANCH_AUTHORITY: allowed\nPASEO_TEAM_TASK_V3_END`);
assert.equal(process.env.PASEO_CODEX_ROLE, undefined);
process.env.PASEO_CODEX_ROLE = "worker"; assert.equal(detectRole(), "worker");
assert.match(blockReasonForTool("worker", null, "Bash", { command: "echo x" }, repo), /read-only/);
assert.match(blockReasonForTool("reviewer", valid, "apply_patch", { command: "*** Begin Patch\n*** Update File: README.md\n*** End Patch" }, repo), /read-only/);
assert.match(blockReasonForTool("reviewer", valid, "Bash", { command: "ls" }, repo), /read-only/);
assert.match(ownedScopeBlockReason(valid, "README.md", repo), /outside OWNED_SCOPE/);
assert.equal(blockReasonForTool("worker", valid, "apply_patch", { command: "*** Begin Patch\n*** Update File: test/new.mjs\n*** End Patch" }, repo), null);
assert.match(blockReasonForTool("worker", valid, "apply_patch", { command: "*** Begin Patch\n*** Update File: test/new.mjs\n*** Update File: README.md\n*** End Patch" }, repo), /outside OWNED_SCOPE/);
assert.match(blockReasonForTool("lead", null, "mcp__paseo__list_agents", {}, repo), /CLI-only/);
assert.match(blockReasonForTool("supervisor", null, "mcp__paseo__list_agents", {}, repo), /CLI-only/);
assert.equal(blockReasonForTool("supervisor", null, "Bash", { command: "$PASEO_TEAM_CLI inspect abc" }, repo), null);
assert.equal(blockReasonForTool("supervisor", null, "PowerShell", { command: "& $env:PASEO_TEAM_CLI inspect abc" }, repo), null);
assert.match(blockReasonForTool("supervisor", null, "Bash", { command: "git status" }, repo), /restricted/);
assert.match(blockReasonForTool("supervisor", null, "PowerShell", { command: "git status" }, repo), /restricted/);
assert.match(blockReasonForTool("lead", null, "Bash", { command: "paseo ls" }, repo), /raw paseo/);
assert.match(gitAuthorityBlockReason("git push origin main", { pushTaskBranch: true }, "T-CODEX"), /branch-scoped/);
assert.equal(gitAuthorityBlockReason("git push -u origin HEAD:refs/heads/agent/T-CODEX", { pushTaskBranch: true }, "T-CODEX"), null);
const home = mkdtempSync(path.join(tmpdir(), "paseo-codex-hook-")); mkdirSync(path.join(home, "hooks"));
const run = (name, event) => spawnSync(process.execPath, [path.join(repo, "codex-orchestration/shared/paseo-team-policy", name)], { env: { ...process.env, TMPDIR: home, PASEO_CODEX_ROLE: "worker" }, input: JSON.stringify(event), encoding: "utf8" });
assert.equal(run("user-prompt-submit.mjs", { session_id: "s", prompt: "plain" }).status, 0);
assert.equal(run("pre-tool-use.mjs", {}).status, 2);
assert.equal(run("pre-tool-use.mjs", []).status, 2);
const denied = run("pre-tool-use.mjs", { session_id: "s", cwd: repo, tool_name: "Bash", tool_input: { command: "git push origin main" } });
assert.equal(denied.status, 0); assert.match(denied.stdout, /permissionDecision.*deny/);
const installRoot = mkdtempSync(path.join(tmpdir(), "paseo-codex-install-"));
const outside = path.join(installRoot, "outside.toml"); writeFileSync(outside, "sentinel");
const codexHome = path.join(installRoot, "codex"); mkdirSync(codexHome); symlinkSync(outside, path.join(codexHome, "paseo-lead.config.toml"));
const install = spawnSync(process.execPath, [path.join(repo, "codex-orchestration/install.mjs"), "--dry-run", "--force"], { env: { ...process.env, CODEX_HOME: codexHome, PASEO_HOME: path.join(installRoot, "paseo"), PASEO_CODEX_ROLES_HOME: path.join(installRoot, "roles") }, encoding: "utf8" });
assert.equal(install.status, 1); assert.match(install.stderr, /symlink target/); assert.equal(readFileSync(outside, "utf8"), "sentinel");
const goodRoot = mkdtempSync(path.join(tmpdir(), "paseo-codex-install-good-"));
const good = spawnSync(process.execPath, [path.join(repo, "codex-orchestration/install.mjs")], { env: { ...process.env, CODEX_HOME: path.join(goodRoot, "codex"), PASEO_HOME: path.join(goodRoot, "paseo"), PASEO_CODEX_ROLES_HOME: path.join(goodRoot, "roles") }, encoding: "utf8" });
assert.equal(good.status, 0, good.stderr); assert.ok(existsSync(path.join(goodRoot, "roles", "lead", "hooks.json"))); assert.ok(!existsSync(path.join(goodRoot, "roles", "lead", "hooks", "hooks.json"))); assert.ok(existsSync(path.join(goodRoot, "paseo", "bin", "paseo-team")));
const goodConfig = JSON.parse(readFileSync(path.join(goodRoot, "paseo", "config.json"), "utf8"));
assert.equal(goodConfig.daemon.mcp.enabled, undefined);
assert.equal(goodConfig.daemon.mcp.injectIntoAgents, false);
assert.equal(goodConfig.agents.providers["codex-lead"].command[0], "codex");
assert.match(goodConfig.agents.providers["codex-lead"].env.PASEO_TEAM_CLI, /paseo-team$/);
const linkedRoot = mkdtempSync(path.join(tmpdir(), "paseo-codex-install-linked-")); const linkedRoles = path.join(linkedRoot, "roles"); const linkedOutside = path.join(linkedRoot, "outside"); mkdirSync(linkedOutside, { recursive: true }); mkdirSync(path.join(linkedRoles, "lead"), { recursive: true }); symlinkSync(linkedOutside, path.join(linkedRoles, "lead", "hooks"));
const linked = spawnSync(process.execPath, [path.join(repo, "codex-orchestration/install.mjs")], { env: { ...process.env, CODEX_HOME: path.join(linkedRoot, "codex"), PASEO_HOME: path.join(linkedRoot, "paseo"), PASEO_CODEX_ROLES_HOME: linkedRoles }, encoding: "utf8" });
assert.equal(linked.status, 1); assert.match(linked.stderr, /symlink directory/);
console.log("[codex-policy] tests passed");
